sudo: required

addons:
  firefox: "30.0"
    
language: ruby

rvm:
  - "2.0.0"
  
env:
  global:
    - CI_NODE_TOTAL=5
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - CI_NODE_INDEX=4

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flashplugin-installer
  - "gem install cucumber"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start --server-args="-screen 0 1024x768x24"

script: "bundle exec rake play"

dist: precise

notifications:
  slack:
    rooms:
      - konquestnow:03bujAjO7LEZC11L9j2ccFH7#notifications
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always

#script:
#- "bundle exec rake knapsack:features"
#- "KNAPSACK_GENERATE_REPORT=true bundle exec rake features"
